appname: "App::BlogAlba"
layout: "main"
charset: "UTF-8"
tz: "Europe/London"
locale: "en_GB"

template: "template_toolkit"
engines:
  template:
    template_toolkit:
      encoding:  'utf8'
      start_tag: '[%'
      end_tag:   '%]'


#Site configuration

#url: https://maff.scot/
name: colourful words and phrases
tagline: techy tangents and general life chatter from a tired sysadmin.
author: Maff
about: A dorky dude who spends too much time with perl.
keywords: "sysadmin,unix,bsd,freebsd,linux,software,web,developer,perl,bash,shell,gentoo,maff,matthew,connelly,dundee,scotland,furry,blog"
blog_prepend: wrote
conf:
  indexable: 1
  per_page: 6
  recent_posts: 8
  rss_publish: 1
  rss_excerpt: 1
  date_format: "%H:%M on %A, %d/%m/%y"
links:
  Twitter: https://twitter.com/maffsie
  Github: https://github.com/Maffsie
